### PR TITLE
1er commit d'antoine

### PR DESCRIPTION
**Pull request by anmuller**
This change is [Reviewable](https://reviewable.io/reviews/ANaaim/hello-word/4)

### CODE REVIEW

**Review by ANaaim — COMMENTED** [review]
test

> *[Reviewable](https://reviewable.io/reviews/ANaaim/hello-word/4#-:-O0mRtZKD9Td-ELwaBOB:bb7p34n)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by ANaaim** [comment]
*[`README.md` line 5 at r1](https://reviewable.io/reviews/ANaaim/hello-word/4#-O0mSJ2x-n-2fZWTu4jO:-O0mSJ2x-n-2fZWTu4jP:b-l32hla) ([raw file](https://github.com/ANaaim/hello-word/blob/90988aa417267a03f69336b630056b14b2de5093/README.md#L5)):*
> ```Markdown
> On rajoute juste du texte dans le code
> 
> J'ai ajouté ma contribution :-)
> ```

Il faut changer ça... avec çà

**Review by anmuller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ANaaim/hello-word/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ANaaim)

___
*[`README.md` line 5 at r1](https://reviewable.io/reviews/ANaaim/hello-word/4#-O0mSJ2x-n-2fZWTu4jO:-O0mSsYo25KK4kYJEdg9:b-3bk2yo) ([raw file](https://github.com/ANaaim/hello-word/blob/90988aa417267a03f69336b630056b14b2de5093/README.md#L5)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Il faut changer ça... avec çà
</blockquote></details>

Non t'as tort

**Review by ANaaim — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ANaaim/hello-word/4#-:-O0mT6vD2buCUzpOQFQU:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion

**Review by ANaaim — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ANaaim/hello-word/4)* status: all files reviewed, 1 unresolved discussion (waiting on @anmuller)

**Pull request merged**
